"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Zap,
  Code,
  Database,
  Smartphone,
  Globe,
  ShoppingCart,
  MessageSquare,
  BarChart3,
  Users,
  FileText,
  Play,
  Download,
  Eye,
  Settings,
  Plus,
  Sparkles,
  Rocket,
  Wand2,
  Cpu,
  Palette,
  Shield,
  Clock,
} from "lucide-react"
import { useToast } from "@/hooks/use-toast"

const appTypes = [
  {
    id: "web",
    name: "Web Application",
    icon: Globe,
    description: "Full-stack web apps with modern UI",
    gradient: "from-blue-500 to-cyan-500",
    bgColor: "bg-blue-50 dark:bg-blue-900/20"
  },
  {
    id: "mobile",
    name: "Mobile App",
    icon: Smartphone,
    description: "Progressive web apps & mobile interfaces",
    gradient: "from-green-500 to-emerald-500",
    bgColor: "bg-green-50 dark:bg-green-900/20"
  },
  {
    id: "dashboard",
    name: "Dashboard",
    icon: BarChart3,
    description: "Analytics and admin dashboards",
    gradient: "from-purple-500 to-pink-500",
    bgColor: "bg-purple-50 dark:bg-purple-900/20"
  },
  {
    id: "ecommerce",
    name: "E-commerce",
    icon: ShoppingCart,
    description: "Online stores and marketplaces",
    gradient: "from-orange-500 to-red-500",
    bgColor: "bg-orange-50 dark:bg-orange-900/20"
  },
  {
    id: "social",
    name: "Social Platform",
    icon: Users,
    description: "Community and social features",
    gradient: "from-indigo-500 to-purple-500",
    bgColor: "bg-indigo-50 dark:bg-indigo-900/20"
  },
  {
    id: "api",
    name: "API Backend",
    icon: Database,
    description: "RESTful APIs and microservices",
    gradient: "from-teal-500 to-cyan-500",
    bgColor: "bg-teal-50 dark:bg-teal-900/20"
  },
  {
    id: "cms",
    name: "Content Management",
    icon: FileText,
    description: "Blogs, CMS, and content platforms",
    gradient: "from-pink-500 to-rose-500",
    bgColor: "bg-pink-50 dark:bg-pink-900/20"
  },
  {
    id: "chatbot",
    name: "AI Chatbot",
    icon: MessageSquare,
    description: "Conversational AI applications",
    gradient: "from-violet-500 to-purple-500",
    bgColor: "bg-violet-50 dark:bg-violet-900/20"
  },
]

const templates = [
  {
    name: "Next.js SaaS Starter",
    category: "SaaS",
    features: ["Auth", "Payments", "Dashboard"],
    gradient: "from-blue-500 to-purple-600",
    icon: Rocket
  },
  {
    name: "React E-commerce",
    category: "E-commerce",
    features: ["Cart", "Checkout", "Inventory"],
    gradient: "from-orange-500 to-red-600",
    icon: ShoppingCart
  },
  {
    name: "Admin Dashboard",
    category: "Dashboard",
    features: ["Charts", "Tables", "Reports"],
    gradient: "from-purple-500 to-pink-600",
    icon: BarChart3
  },
  {
    name: "Blog CMS",
    category: "CMS",
    features: ["Rich Editor", "SEO", "Comments"],
    gradient: "from-green-500 to-teal-600",
    icon: FileText
  },
  {
    name: "Social Media App",
    category: "Social",
    features: ["Feed", "Profiles", "Messaging"],
    gradient: "from-indigo-500 to-blue-600",
    icon: Users
  },
  {
    name: "API Backend",
    category: "API",
    features: ["REST", "GraphQL", "WebSocket"],
    gradient: "from-cyan-500 to-blue-600",
    icon: Database
  },
]

export default function Dashboard() {
  const [prompt, setPrompt] = useState("")
  const [selectedType, setSelectedType] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [generatedCode, setGeneratedCode] = useState("")
  const { toast } = useToast()

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      toast({
        title: "✨ Describe Your Vision",
        description: "Please enter a description for your app to get started!",
        variant: "destructive",
      })
      return
    }

    setIsGenerating(true)

    // Simulate AI generation with better mock code
    try {
      await new Promise(resolve => setTimeout(resolve, 3000))

      const mockCode = `// 🚀 Generated by Codiner AI - Next-Generation App Builder
// 📱 App: ${prompt}
// 🎯 Type: ${selectedType}
// 🛠️  Tech Stack: Next.js 14, TypeScript, Tailwind CSS, Supabase

'use client'

import { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { supabase } from '@/lib/supabase'

interface AppData {
  id: string
  title: string
  description: string
  status: 'active' | 'pending' | 'completed'
  created_at: string
}

export default function GeneratedApp() {
  const [data, setData] = useState<AppData[]>([])
  const [loading, setLoading] = useState(false)
  const [searchTerm, setSearchTerm] = useState('')

  useEffect(() => {
    fetchData()
  }, [])

  const fetchData = async () => {
    setLoading(true)
    try {
      const { data: result, error } = await supabase
        .from('app_data')
        .select('*')
        .order('created_at', { ascending: false })

      if (error) throw error
      setData(result || [])
    } catch (error) {
      console.error('❌ Error fetching data:', error)
      toast.error('Failed to load data')
    } finally {
      setLoading(false)
    }
  }

  const filteredData = data.filter(item =>
    item.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    item.description.toLowerCase().includes(searchTerm.toLowerCase())
  )

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 dark:from-slate-900 dark:to-slate-800">
      <div className="container mx-auto px-4 py-8 max-w-7xl">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent mb-4">
            ${prompt}
          </h1>
          <p className="text-xl text-slate-600 dark:text-slate-300 max-w-2xl mx-auto">
            AI-generated ${selectedType} application with modern design and full functionality
          </p>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <Card className="card-hover glass">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium text-slate-600 dark:text-slate-400">
                Total Items
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-blue-600">
                {data.length}
              </div>
              <p className="text-sm text-slate-500">Records in database</p>
            </CardContent>
          </Card>

          <Card className="card-hover glass">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium text-slate-600 dark:text-slate-400">
                Active Status
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-green-600">
                {data.filter(item => item.status === 'active').length}
              </div>
              <p className="text-sm text-slate-500">Active items</p>
            </CardContent>
          </Card>

          <Card className="card-hover glass">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium text-slate-600 dark:text-slate-400">
                Completion Rate
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-purple-600">
                {data.length > 0 ? Math.round((data.filter(item => item.status === 'completed').length / data.length) * 100) : 0}%
              </div>
              <p className="text-sm text-slate-500">Tasks completed</p>
            </CardContent>
          </Card>
        </div>

        {/* Search and Actions */}
        <div className="flex flex-col sm:flex-row gap-4 mb-8">
          <Input
            placeholder="🔍 Search items..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="input-focus"
          />
          <Button
            onClick={fetchData}
            disabled={loading}
            className="btn-gradient"
          >
            {loading ? '⏳ Loading...' : '🔄 Refresh Data'}
          </Button>
        </div>

        {/* Data Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredData.map((item) => (
            <Card key={item.id} className="card-hover glass">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <CardTitle className="text-lg font-semibold">
                    {item.title}
                  </CardTitle>
                  <Badge
                    variant={item.status === 'completed' ? 'default' : item.status === 'active' ? 'secondary' : 'outline'}
                    className="ml-2"
                  >
                    {item.status}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-slate-600 dark:text-slate-300 mb-4">
                  {item.description}
                </p>
                <div className="flex items-center justify-between text-sm text-slate-500">
                  <span>📅 {new Date(item.created_at).toLocaleDateString()}</span>
                  <Button variant="ghost" size="sm">
                    ✏️ Edit
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Empty State */}
        {filteredData.length === 0 && !loading && (
          <div className="text-center py-12">
            <div className="w-24 h-24 mx-auto mb-6 bg-gradient-to-br from-blue-100 to-purple-100 dark:from-blue-900/20 dark:to-purple-900/20 rounded-full flex items-center justify-center">
              <Sparkles className="w-12 h-12 text-blue-600 dark:text-blue-400" />
            </div>
            <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2">
              {searchTerm ? 'No items match your search' : 'No data yet'}
            </h3>
            <p className="text-slate-600 dark:text-slate-400 mb-6">
              {searchTerm ? 'Try adjusting your search terms' : 'Your AI-generated app is ready to use!'}
            </p>
            <Button className="btn-gradient">
              <Plus className="w-4 h-4 mr-2" />
              Add First Item
            </Button>
          </div>
        )}

        {/* Generated Features Showcase */}
        <Card className="mt-12 card-hover glass">
          <CardHeader>
            <CardTitle className="flex items-center">
              <Sparkles className="w-5 h-5 mr-2 text-yellow-500" />
              AI-Generated Features
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <Badge variant="secondary" className="justify-center py-2">
                ⚡ Real-time Updates
              </Badge>
              <Badge variant="secondary" className="justify-center py-2">
                🎨 Modern UI/UX
              </Badge>
              <Badge variant="secondary" className="justify-center py-2">
                📱 Responsive Design
              </Badge>
              <Badge variant="secondary" className="justify-center py-2">
                🔒 Type Safety
              </Badge>
              <Badge variant="secondary" className="justify-center py-2">
                🚀 Performance
              </Badge>
              <Badge variant="secondary" className="justify-center py-2">
                🔄 Auto Sync
              </Badge>
              <Badge variant="secondary" className="justify-center py-2">
                📊 Analytics
              </Badge>
              <Badge variant="secondary" className="justify-center py-2">
                🔧 API Ready
              </Badge>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}`

      setGeneratedCode(mockCode)
      toast({
        title: "🎉 Success!",
        description: "Your AI-powered app has been generated successfully! ✨",
      })
    } catch (error) {
      toast({
        title: "❌ Error",
        description: "Failed to generate app. Please try again.",
        variant: "destructive",
      })
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <div className="w-full max-w-6xl mx-auto space-y-8 animate-fade-in">
      {/* Hero Section */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-blue-600 via-purple-600 to-pink-600 p-8 md:p-12 mb-8 mx-auto max-w-7xl">
        <div className="absolute inset-0 bg-black/10"></div>
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-white/10 rounded-full blur-3xl"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-white/5 rounded-full blur-3xl"></div>

        <div className="relative z-10">
          <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-8">
            <div className="flex-1">
              <div className="flex items-center mb-4">
                <div className="w-12 h-12 bg-white/20 backdrop-blur-sm rounded-2xl flex items-center justify-center mr-4">
                  <Sparkles className="w-6 h-6 text-white" />
                </div>
                <Badge className="bg-white/20 text-white border-white/30">
                  ✨ 1000+ Features Available
                </Badge>
              </div>

              <h1 className="text-4xl md:text-6xl font-bold text-white mb-4 leading-tight">
                AI App Generator
                <span className="block text-2xl md:text-3xl font-light text-white/80 mt-2">
                  Build Anything with Natural Language
                </span>
              </h1>

              <p className="text-xl text-white/90 mb-8 max-w-2xl leading-relaxed">
                Transform your ideas into production-ready applications in seconds.
                No coding experience required - just describe what you want to build.
              </p>

              <div className="flex flex-wrap gap-4">
                <div className="flex items-center bg-white/10 backdrop-blur-sm rounded-full px-4 py-2">
                  <Zap className="w-4 h-4 text-yellow-300 mr-2" />
                  <span className="text-white text-sm">Instant Generation</span>
                </div>
                <div className="flex items-center bg-white/10 backdrop-blur-sm rounded-full px-4 py-2">
                  <Shield className="w-4 h-4 text-green-300 mr-2" />
                  <span className="text-white text-sm">Enterprise Ready</span>
                </div>
                <div className="flex items-center bg-white/10 backdrop-blur-sm rounded-full px-4 py-2">
                  <Cpu className="w-4 h-4 text-blue-300 mr-2" />
                  <span className="text-white text-sm">250+ AI Models</span>
                </div>
              </div>
            </div>

            <div className="flex-1 lg:flex justify-end hidden lg:block">
              <div className="relative">
                <div className="w-80 h-80 bg-white/10 backdrop-blur-sm rounded-3xl p-6 border border-white/20">
                  <div className="w-full h-full bg-gradient-to-br from-blue-400/20 to-purple-400/20 rounded-2xl flex items-center justify-center">
                    <div className="text-center">
                      <Wand2 className="w-16 h-16 text-white mx-auto mb-4" />
                      <h3 className="text-white font-semibold text-lg mb-2">Your App Here</h3>
                      <p className="text-white/70 text-sm">AI-generated in seconds</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-8 max-w-4xl mx-auto">
        <Card className="card-hover glass text-center">
          <CardContent className="pt-6">
            <div className="text-3xl font-bold text-blue-600 mb-2">1,247</div>
            <p className="text-sm text-slate-600 dark:text-slate-400">AI Credits Used</p>
          </CardContent>
        </Card>

        <Card className="card-hover glass text-center">
          <CardContent className="pt-6">
            <div className="text-3xl font-bold text-green-600 mb-2">47</div>
            <p className="text-sm text-slate-600 dark:text-slate-400">Apps Generated</p>
          </CardContent>
        </Card>

        <Card className="card-hover glass text-center">
          <CardContent className="pt-6">
            <div className="text-3xl font-bold text-purple-600 mb-2">24/7</div>
            <p className="text-sm text-slate-600 dark:text-slate-400">AI Availability</p>
          </CardContent>
        </Card>

        <Card className="card-hover glass text-center">
          <CardContent className="pt-6">
            <div className="text-3xl font-bold text-orange-600 mb-2">∞</div>
            <p className="text-sm text-slate-600 dark:text-slate-400">Possibilities</p>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="generate" className="space-y-8">
        <TabsList className="grid w-full max-w-md mx-auto grid-cols-3 h-12 bg-white/50 backdrop-blur-sm border border-white/20">
          <TabsTrigger value="generate" className="text-sm font-medium">🎨 Generate App</TabsTrigger>
          <TabsTrigger value="templates" className="text-sm font-medium">📚 Templates</TabsTrigger>
          <TabsTrigger value="projects" className="text-sm font-medium">🚀 My Projects</TabsTrigger>
        </TabsList>

        {/* Generate Tab */}
        <TabsContent value="generate" className="space-y-8">
          {/* App Type Selection */}
          <Card className="card-hover glass border-0 shadow-xl">
            <CardHeader className="text-center pb-2">
              <CardTitle className="text-2xl text-gradient">Choose Your App Type</CardTitle>
              <CardDescription className="text-base">
                Select the perfect foundation for your application
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {appTypes.map((type) => (
                  <div
                    key={type.id}
                    onClick={() => setSelectedType(type.id)}
                    className={`group p-6 rounded-2xl cursor-pointer transition-all duration-300 border-2 card-hover ${
                      selectedType === type.id
                        ? `bg-gradient-to-br ${type.gradient} text-white border-transparent shadow-lg scale-105`
                        : `${type.bgColor} border-slate-200 dark:border-slate-700 hover:border-slate-300 group-hover:scale-105`
                    }`}
                  >
                    <type.icon className={`h-10 w-10 mb-4 transition-colors ${
                      selectedType === type.id ? 'text-white' : 'text-slate-600 dark:text-slate-400 group-hover:text-slate-800'
                    }`} />
                    <h3 className={`font-bold text-lg mb-2 ${
                      selectedType === type.id ? 'text-white' : 'text-slate-900 dark:text-slate-100'
                    }`}>
                      {type.name}
                    </h3>
                    <p className={`text-sm leading-relaxed ${
                      selectedType === type.id ? 'text-white/80' : 'text-slate-600 dark:text-slate-400'
                    }`}>
                      {type.description}
                    </p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Prompt Input */}
          <Card className="card-hover glass border-0 shadow-xl">
            <CardHeader>
              <CardTitle className="flex items-center text-gradient">
                <Wand2 className="w-6 h-6 mr-3 text-purple-500" />
                Describe Your Perfect App
              </CardTitle>
              <CardDescription className="text-base">
                Be specific about features, design preferences, and functionality. The more detail, the better the result.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <Textarea
                placeholder="Example: 'Create a modern task management app with a clean dashboard, drag-and-drop task organization, real-time collaboration, dark mode support, and integration with Google Calendar. Include user authentication, project management, time tracking, and export to PDF.'"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                className="min-h-[140px] text-base resize-none input-focus border-2"
              />

              <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
                <div className="flex flex-wrap items-center gap-4">
                  <Select>
                    <SelectTrigger className="w-[200px] h-12 border-2 input-focus">
                      <SelectValue placeholder="🤖 Choose AI Model" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="gpt-4">
                        <div className="flex items-center">
                          <div className="w-2 h-2 bg-green-500 rounded-full mr-3"></div>
                          GPT-4 (Recommended)
                        </div>
                      </SelectItem>
                      <SelectItem value="claude">
                        <div className="flex items-center">
                          <div className="w-2 h-2 bg-blue-500 rounded-full mr-3"></div>
                          Claude Sonnet
                        </div>
                      </SelectItem>
                      <SelectItem value="gemini">
                        <div className="flex items-center">
                          <div className="w-2 h-2 bg-purple-500 rounded-full mr-3"></div>
                          Gemini Pro
                        </div>
                      </SelectItem>
                      <SelectItem value="local">
                        <div className="flex items-center">
                          <div className="w-2 h-2 bg-orange-500 rounded-full mr-3"></div>
                          Local Models
                        </div>
                      </SelectItem>
                    </SelectContent>
                  </Select>

                  <Badge variant="outline" className="h-8 px-4 border-2 border-blue-200 text-blue-700 bg-blue-50 dark:bg-blue-900/20">
                    <Clock className="w-3 h-3 mr-1" />
                    ~50 Credits
                  </Badge>
                </div>

                <Button
                  onClick={handleGenerate}
                  disabled={isGenerating || !prompt.trim()}
                  size="lg"
                  className="btn-gradient h-12 px-8 text-lg font-semibold shadow-2xl"
                >
                  {isGenerating ? (
                    <>
                      <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-3"></div>
                      Generating Your App...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-5 w-5 mr-3" />
                      Generate App
                    </>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Generated Code Preview */}
          {generatedCode && (
            <Card className="card-hover glass border-0 shadow-2xl">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="flex items-center text-2xl text-gradient">
                      <Rocket className="w-6 h-6 mr-3 text-green-500" />
                      Your AI-Generated App is Ready!
                    </CardTitle>
                    <CardDescription className="text-base mt-2">
                      Complete, production-ready code with modern architecture and best practices
                    </CardDescription>
                  </div>
                  <div className="flex space-x-3">
                    <Button variant="outline" size="lg" className="border-2 hover:bg-slate-50 dark:hover:bg-slate-800">
                      <Eye className="h-5 w-5 mr-2" />
                      Live Preview
                    </Button>
                    <Button variant="outline" size="lg" className="border-2 hover:bg-slate-50 dark:hover:bg-slate-800">
                      <Download className="h-5 w-5 mr-2" />
                      Download Code
                    </Button>
                    <Button size="lg" className="btn-gradient shadow-lg">
                      <Play className="h-5 w-5 mr-2" />
                      Deploy Now
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <pre className="bg-slate-900 dark:bg-slate-800 text-slate-100 p-6 rounded-xl overflow-x-auto text-sm max-h-96 overflow-y-auto border border-slate-700 shadow-inner">
                  <code>{generatedCode}</code>
                </pre>
              </CardContent>
            </Card>
          )}
        </TabsContent>

        {/* Templates Tab */}
        <TabsContent value="templates" className="space-y-8">
          <div className="text-center mb-8">
            <h2 className="text-3xl font-bold text-gradient mb-4">Professional Templates</h2>
            <p className="text-slate-600 dark:text-slate-400 max-w-2xl mx-auto">
              Jumpstart your projects with our curated collection of production-ready templates
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {templates.map((template, index) => (
              <Card key={index} className="card-hover glass border-2 border-slate-200 dark:border-slate-700 hover:border-slate-300 overflow-hidden group">
                <CardHeader className="pb-4">
                  <div className={`w-16 h-16 bg-gradient-to-br ${template.gradient} rounded-2xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300`}>
                    <template.icon className="w-8 h-8 text-white" />
                  </div>
                  <CardTitle className="text-xl font-bold">{template.name}</CardTitle>
                  <CardDescription className="text-base">{template.category}</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2 mb-6">
                    {template.features.map((feature, i) => (
                      <Badge key={i} variant="secondary" className="text-xs px-3 py-1 bg-slate-100 dark:bg-slate-800">
                        {feature}
                      </Badge>
                    ))}
                  </div>
                  <Button className="w-full btn-gradient group-hover:shadow-lg transition-shadow">
                    Use This Template
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>

        {/* Projects Tab */}
        <TabsContent value="projects" className="space-y-8">
          <div className="text-center py-16 max-w-2xl mx-auto">
            <div className="w-32 h-32 mx-auto mb-8 bg-gradient-to-br from-blue-100 to-purple-100 dark:from-blue-900/20 dark:to-purple-900/20 rounded-full flex items-center justify-center">
              <Code className="w-16 h-16 text-blue-600 dark:text-blue-400" />
            </div>
            <h3 className="text-3xl font-bold text-slate-900 dark:text-slate-100 mb-4">
              Ready to Build Something Amazing?
            </h3>
            <p className="text-xl text-slate-600 dark:text-slate-400 mb-8 max-w-2xl mx-auto leading-relaxed">
              Your AI-powered development journey starts here. Generate your first app and see the future of coding.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button size="lg" className="btn-gradient shadow-xl px-8">
                <Plus className="h-5 w-5 mr-2" />
                Create Your First Project
              </Button>
              <Button variant="outline" size="lg" className="border-2 hover:bg-slate-50 dark:hover:bg-slate-800 px-8">
                <Palette className="h-5 w-5 mr-2" />
                Browse Templates
              </Button>
            </div>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  )
}